# Site settings
title: Event Maker
email: pocksoft@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Event Maker is an awsome app designed to create calendar events
  with minimum fuss and maximum efficiency
baseurl: "/eventmaker" # the subpath of your site, e.g. /blog/
url: "http://pocket.software" # the base hostname & protocol for your site
twitter_username: jjnevis
github_username:  jjnevis
permalink: pretty
# Build settings
markdown: kramdown
